name: build-docs
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: explorateur-media/package-lock.json

      - name: Install deps
        working-directory: ./explorateur-media
        run: |
          npm install --no-audit --no-fund

      - name: Angular CLI (local via npx -p npm v11)
        working-directory: ./explorateur-media
        run: |
          npx --yes -p @angular/cli@20 ng version

      - name: Build for Pages into docs/
        working-directory: ./explorateur-media
        run: |
          npx --yes -p @angular/cli@20 ng build --configuration production --output-path ../docs --base-href "/explorateur_media/"

      - name: Move files to root of docs
        run: |
          mv docs/browser/en-US/* docs/
          rm -rf docs/browser

      - name: Create .nojekyll (empêche GitHub Pages d’ignorer assets)
        run: |
          touch docs/.nojekyll
          echo "/*    /index.html   200" > docs/_redirects || true

      - name: Commit docs back to main
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "build: update docs for GitHub Pages"
          file_pattern: docs/**
